name: "ci"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Set up JDK 17 and Maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          maven-version: 3.8.5

      - name: Run Tests
        run: mvn --batch-mode test -q

      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@10.0.50.137:22/minecraft-helper"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}