CREATE TABLE player_view_events
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id  UUID                                    NOT NULL,
    ip_address VARCHAR(255)                            NOT NULL,
    viewed_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_player_view_events PRIMARY KEY (id),
    CONSTRAINT fk_player_view_events_player_id FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE CASCADE
);