-- ALTER TABLE ... RENAME does not rename the table's constraints (PostgreSQL keeps their
-- original names), so the tracker_* table renames in V44 left every constraint and
-- constraint-backed index under its old table prefix. Rename them all to match: pkeys,
-- the (ip, port) unique key, the FKs on the child tables, and the NOT NULL checks
-- (named since modern PostgreSQL versions). Purely cosmetic — object names only.
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_pkey TO tracker_servers_pkey;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_ip_port_key TO tracker_servers_ip_port_key;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_uuid_not_null TO tracker_servers_uuid_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_ip_not_null TO tracker_servers_ip_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_port_not_null TO tracker_servers_port_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_first_seen_not_null TO tracker_servers_first_seen_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_last_updated_not_null TO tracker_servers_last_updated_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_online_count_not_null TO tracker_servers_online_count_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_max_players_not_null TO tracker_servers_max_players_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_modded_not_null TO tracker_servers_modded_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_prevents_chat_reports_not_null TO tracker_servers_prevents_chat_reports_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_enforces_secure_chat_not_null TO tracker_servers_enforces_secure_chat_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_previews_chat_not_null TO tracker_servers_previews_chat_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_sample_count_not_null TO tracker_servers_sample_count_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_honeypot_not_null TO tracker_servers_honeypot_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_consecutive_offline_not_null TO tracker_servers_consecutive_offline_not_null;
ALTER TABLE tracker_servers RENAME CONSTRAINT tracked_servers_last_refreshed_not_null TO tracker_servers_last_refreshed_not_null;

ALTER TABLE tracker_player_history RENAME CONSTRAINT player_history_pkey TO tracker_player_history_pkey;
ALTER TABLE tracker_player_history RENAME CONSTRAINT player_history_server_uuid_fkey TO tracker_player_history_server_uuid_fkey;
ALTER TABLE tracker_player_history RENAME CONSTRAINT player_history_server_uuid_not_null TO tracker_player_history_server_uuid_not_null;
ALTER TABLE tracker_player_history RENAME CONSTRAINT player_history_player_uuid_not_null TO tracker_player_history_player_uuid_not_null;
ALTER TABLE tracker_player_history RENAME CONSTRAINT player_history_username_not_null TO tracker_player_history_username_not_null;
ALTER TABLE tracker_player_history RENAME CONSTRAINT player_history_first_seen_not_null TO tracker_player_history_first_seen_not_null;
ALTER TABLE tracker_player_history RENAME CONSTRAINT player_history_last_seen_not_null TO tracker_player_history_last_seen_not_null;
ALTER TABLE tracker_player_history RENAME CONSTRAINT player_history_times_seen_not_null TO tracker_player_history_times_seen_not_null;

ALTER TABLE tracker_server_online_history RENAME CONSTRAINT server_online_history_pkey TO tracker_server_online_history_pkey;
ALTER TABLE tracker_server_online_history RENAME CONSTRAINT server_online_history_server_uuid_fkey TO tracker_server_online_history_server_uuid_fkey;
ALTER TABLE tracker_server_online_history RENAME CONSTRAINT server_online_history_server_uuid_not_null TO tracker_server_online_history_server_uuid_not_null;
ALTER TABLE tracker_server_online_history RENAME CONSTRAINT server_online_history_sampled_at_not_null TO tracker_server_online_history_sampled_at_not_null;
ALTER TABLE tracker_server_online_history RENAME CONSTRAINT server_online_history_online_not_null TO tracker_server_online_history_online_not_null;
ALTER TABLE tracker_server_online_history RENAME CONSTRAINT server_online_history_max_not_null TO tracker_server_online_history_max_not_null;

ALTER TABLE tracker_progress RENAME CONSTRAINT scan_progress_pkey TO tracker_progress_pkey;
ALTER TABLE tracker_progress RENAME CONSTRAINT scan_progress_id_not_null TO tracker_progress_id_not_null;
ALTER TABLE tracker_progress RENAME CONSTRAINT scan_progress_seed_not_null TO tracker_progress_seed_not_null;
ALTER TABLE tracker_progress RENAME CONSTRAINT scan_progress_permuted16_pos_not_null TO tracker_progress_permuted16_pos_not_null;
ALTER TABLE tracker_progress RENAME CONSTRAINT scan_progress_offset24_not_null TO tracker_progress_offset24_not_null;
ALTER TABLE tracker_progress RENAME CONSTRAINT scan_progress_state_not_null TO tracker_progress_state_not_null;
ALTER TABLE tracker_progress RENAME CONSTRAINT scan_progress_updated_at_not_null TO tracker_progress_updated_at_not_null;